apiVersion: skaffold/v4beta6
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: registration
      context: registration
      requires:
        - image: base
          alias: BASE
    - image: database
      context: database
    - image: base
      context: base
manifests:
  rawYaml:
    - registration/k8s/*
    - database/k8s/*
portForward:
  - resourceType: deployment
    resourceName: registration
    port: http
    localPort: 3000
