apiVersion: skaffold/v4beta6
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: external-services
      context: external-services
    - image: contractor
      context: contractor
    - image: auth
      context: auth
manifests:
  rawYaml:
    - k8s/external-services/*
    - k8s/contractor/*
    - k8s/mongodb/*
    - k8s/auth/*
    - k8s/postgresdb/*
    - k8s/networking/*
portForward:
  - resourceType: deployment
    resourceName: auth
    port: http
    localPort: 3000
  - resourceType: deployment
    resourceName: external-services
    port: http
    localPort: 3001
  - resourceType: deployment
    resourceName: contractor
    port: http
    localPort: 3002
