apiVersion: skaffold/v4beta6
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: external-services
      context: external-services
      requires:
        - image: base
          alias: BASE
    - image: auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: base
      context: base
manifests:
  rawYaml:
    - k8s/external-services/*
    - k8s/auth/*
    - k8s/mongodb/*
    - k8s/networking/
portForward:
  - resourceType: deployment
    resourceName: external-services
    port: http
    localPort: 3001
  - resourceType: deployment
    resourceName: auth
    port: http
    localPort: 3000
