apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
  labels:
    app: registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - name: registration
          image: registration
          ports:
            - containerPort: 3000
              name: http
