apiVersion: v1
kind: Service
metadata:
  name: registration
  labels:
    app: registration
spec:
  clusterIP: None
  ports:
    - port: 3000
      name: registration
  selector:
    app: registration
