apiVersion: v1
kind: Service
metadata:
  name: external-services
  labels:
    app: external-services
spec:
  clusterIP: None
  ports:
    - port: 3001
      name: external-services
  selector:
    app: external-services
