kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume # Sets PV's name
  labels:
    type: local # Sets PV's type to local
    app: postgresdb
spec:
  #storageClassName: "hostpath"
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
