apiVersion: v1
kind: Service
metadata:
  name: postgresdb # Sets service name
  labels:
    app: postgresdb # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432 # Sets port to run the postgres application
  selector:
    app: postgresdb
