kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim # Sets name of PVC
  labels:
    app: postgresdb
spec:
  #storageClassName: "hostpath"
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: 5Gi # Sets volume size
