apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgresdb
  namespace: default
spec:
  replicas: 1
  image: postgres:15.4-alpine3.18
  database:
    size: 1Gi
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresdb-secret
          key: superUserPassword
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresdb-secret
          key: replicationUserPassword
