apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-mongo
  template:
    metadata:
      labels:
        app: users-mongo
    spec:
      containers:
        - name: users-mongo
          image: mongo