apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host:
      http:
        paths:
          - path: /api/auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3000
          - path: /api/external_services/*/?(.*)
            pathType: Prefix
            backend:
              service:
                name: external-services
                port:
                  number: 3001
          - path: /api/contractor/*/?(.*)
            pathType: Prefix
            backend:
              service:
                name: contractor
                port:
                  number: 3002
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  number: 3003
